### PR TITLE
Added (After)ElementSave plugin event

### PR DESCRIPTION
**Pull request by AnsisMalins**
I realized I need one more event for the Perforce plugin to work correctly. It's named ElementSave to match the ProjectSave event.

### CODE REVIEW

**Comment by vchelaru** [comment]
Could we change the name to "AfterElementSave" as the element has already been saved? I don't know if there is a BeforeElementSave but I could see plugins needing before and after logic on saving.

**Comment by bjorn** [comment]
I think the point is, if "AfterElementSave" is better then "ProjectSave" should be renamed to "AfterProjectSave" as well. I think in either case, it is not a reason not to merge this.

**Comment by AnsisMalins** [comment]
Implemented Bjorn's suggestion.

**Comment by bjorn** [comment]
My suggestion was to either rename neither or both. Now you renamed one of them. :-)

**Comment by AnsisMalins** [comment]
What? It's now BeforeProjctSave, AfterProjectSave, BeforeElementSave, and AfterElementSave.

**Comment by bjorn** [comment]
@AnsisMalins Ah, I was looking at `ProjectLoad` and wondered why it wasn't `AfterProjectLoad` now.

**Comment by bjorn** [comment]
Personally I prefer `ProjectSaved` rather than `AfterProjectSave`, btw.

**Comment by AnsisMalins** [comment]
Naming convention flamewar go!

**Pull request merged**
